### ISSUE TITLE
Use with proxy registry may lead to "weird" behavior

### ISSUE THREAD

**Issue by sylvainOL** [ckotzbauer/sbom-operator#290]
Hello,

as promised, I've tried to use with proxy:

here's my conf:

```yaml
dtrack-base-url:
    http://dependency-track-backend.dependency-track.svc.cluster.local
  fallback-pull-secret: gitlab-docker-auth
  format: cyclonedx
  ignore-annotations: true
  registry-proxy:
    docker.io=docker.stable.lb.innovation.nif-cd.fr
  targets: dtrack
```

The thing is at end of run, it'll suppress all `docker.stable.lb.innovation.nif-cd.fr/*` projects in dtrack as they're not present on the cluster :(

```
time="2023-01-18T15:25:06Z" level=info msg="Removing kubernetes-cluster=default tag from project docker.stable.lb.innovation.nif-cd.fr/public-dockerhub/minio/operator:v4.5.8"
time="2023-01-18T15:25:06Z" level=info msg="Image not running in any cluster - removing docker.stable.lb.innovation.nif-cd.fr/public-dockerhub/minio/operator:v4.5.8"

but:
```shell
$ kubectl describe pod minio-operator-697dbbcc54-94hkh | grep Image:
    Image:         docker.io/istio/proxyv2:1.16.1
    Image:         docker.io/istio/proxyv2:1.16.1
    Image:          minio/operator:v4.5.8
```
