### ISSUE TITLE
[Question] - Exclude certain images from scanning

### ISSUE THREAD

**Issue by cloudmatt** [ckotzbauer/sbom-operator#415]
👋🏻 - Are their any examples available of how to use the `namespace-label-selector` and `pod-label-selector` parameters to this? I've tried a few variations but get nothing but errors. So clearly i'm not understanding something here.

**Config**
Attempt 1

```yaml
args:
  targets: dtrack
  format: cyclonedx
  dtrack-base-url: my-cool-url
  dtrack-api-key: notanapikey
  kubernetes-cluster-id: cluster-name
  namespace-label-selector: 'notin kube-system'
```
```shell
time="2023-06-06T00:30:00Z" level=info msg="Execute background-service"
time="2023-06-06T00:30:00Z" level=error msg="failed to list namespaces with selector: notin kube-system, abort background-service" error="failed to list namespaces: unable to parse requirement: found 'kube-system', expected: in, notin, =, ==, !=, gt, lt"
```

Attempt 2

```yaml
args:
  targets: dtrack
  format: cyclonedx
  dtrack-base-url: my-cool-url
  dtrack-api-key: notanapikey
  kubernetes-cluster-id: cluster-name
  namespace-label-selector: 'notin (kube-system)'
```
```shell
time="2023-06-05T19:30:00Z" level=info msg="Execute background-service"
time="2023-06-05T19:30:00Z" level=error msg="failed to list namespaces with selector: notin (kube-system), abort background-service" error="failed to list namespaces: unable to parse requirement: found '(', expected: in, notin, =, ==, !=, gt, lt"
```
