### ISSUE TITLE
The clusterrole is missing a confimag rule

### ISSUE THREAD

**Issue by bouenou** [ckotzbauer/sbom-operator#437]
Hi,

We install `sbom-operator` with the helm chart. We have noticed that` sbom-operator ` fails to use `configmap` as a target because of missing rule in the clusterrole. So, it would be good to add a rule like the one below to the clusterrole template of the helm chart.

```
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - list
  - delete
```
