### ISSUE TITLE
Private registry authentication error

### ISSUE THREAD

**Issue by bLoginow** [ckotzbauer/sbom-operator#486]
I am trying to scan images that are located in a private harbor registry but can't get auth to work.
This is the error message i get:
```
time="2023-09-21T07:09:39Z" level=error msg="Source-Creation failed" error="failed to construct source from input registry:myregistry.com/myimage@sha256:0587e7c68dce109536c16a222f50e0459cb062cb08ff323fa467292368429af4: could not fetch image \"myregistry.com/myimage@sha256:0587e7c68dce109536c16a222f50e0459cb062cb08ff323fa467292368429af4\": scheme \"registry\" specified; image retrieval using scheme parsing (myregistry.com/myimage@sha256:0587e7c68dce109536c16a222f50e0459cb062cb08ff323fa467292368429af4) was unsuccessful: unable to use OciRegistry source: failed to get image descriptor from registry: GET https://myregistry.com/v2/myimage/manifests/sha256:0587e7c68dce109536c16a222f50e0459cb062cb08ff323fa467292368429af4: UNAUTHORIZED: unauthorized to access repository: myimage, action: pull: unauthorized to access repository: myimage, action: pull; image retrieval without scheme parsing (registry:myregistry.com/myimage@sha256:0587e7c68dce109536c16a222f50e0459cb062cb08ff323fa467292368429af4) was unsuccessful: unable to determine image source"
```

I have a docker secret on the pod that is scanned, as well as on the sbom operator. Furthermore the same secret is configured as "fallback-pull-secret" in addition.

The secrets look like that:
```
apiVersion: v1
data:
  .dockerconfigjson: xxxxx
kind: Secret
metadata:
  creationTimestamp: "2023-09-15T16:38:08Z"
  name: registry-credentials
  namespace: vulnerability-operator
type: kubernetes.io/dockerconfigjson
```

The secret content is the following:
```
{
    "auths": {
        "https://registry.hub.docker.com/": {
            "username": "myuser",
            "password": "mypassword",
            "auth": "myAuth"
        },
        "https://myregistry-otherlocation.com/": {
            "username": "myuser",
            "password": "mypassword",
            "auth": "myAuth"
        },
        "https://myregistry.com/": {
            "username": "myuser",
            "password": "mypassword",
            "auth": "myAuth"
        }
    }
}
```
Chart config:
```
image:
  pullSecrets:
    - name: registry-credentials

args:
  git-author-email: mymail@myprovider.com
  git-author-name: sbom-operator
  git-branch: master
  git-repository: https://github.com/myCompany/sboms
  targets: git
  verbosity: info
  fallback-pull-secret: registry-credentials

envVars:
  - name: SBOM_GIT_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: git-access-token-sbom
        key: token

resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 1500m
    memory: 3Gi

securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile: null
```
Could the sbom operator have issues if the secret contains multiple registry credentials? Because otherwise it is a valid docker config and also works everywhere else in the cluster.
