### ISSUE TITLE
Proxy registry config is not working as expected

### ISSUE THREAD

**Issue by zbaranow** [ckotzbauer/sbom-operator#645]
Hello,

It appears that even after the commit https://github.com/ckotzbauer/sbom-operator/commit/fdb76e5835d081b3aec119c748bacaa5ab8d136b, the issue described in https://github.com/ckotzbauer/sbom-operator/issues/290 is not completely resolved.

I am running the operator with the following configuration:

```
args:
  targets: dtrack
  dtrack-base-url: "{{ SBOM_DTRACK_URL }}"
  dtrack-api-key: "<path:{{ SBOM_DTRACK_KEY_VAULT_PATH }}>"
  kubernetes-cluster-id: "{{ DNS_ZONE }}"
  registry-proxy: "docker.io=docker-proxy.company.net"
  format: cyclonedx
  verbosity: {{ SBOM_LOG_LEVEL }}
  ignore-annotations: true
```

Initially, all images are correctly registered in dtrack, with all docker.io images being mapped to docker-proxy.company.net. However, they are soon marked for removal because the operator cannot find them on the cluster (the mapping is not applied during pod detection).

```
time="2024-05-30T09:27:50Z" level=info msg="Processing image docker.io/library/traefik@sha256:1957e3314f435c85b3a19f7babd53c630996aa1af65d1f479d75539251b1e112"
time="2024-05-30T09:28:11Z" level=info msg="Sending SBOM to Dependency Track (project=docker-proxy.company.net/traefik, version=v2.10.6)"
.....
time="2024-05-30T09:30:47Z" level=info msg="Removing kubernetes-cluster=bigeys-hp.company.net tag from project docker-proxy.company.net/traefik:v2.10.6"
time="2024-05-30T09:30:47Z" level=info msg="Image not running in any cluster - removing docker-proxy.company.net/traefik:v2.10.6"
```

Of course, the example traefik pod was running all the time.

Most likely the root cause of the problem is a lack of mapping in the informer function that loads pods from the cluster:
 https://github.com/ckotzbauer/sbom-operator/blob/dc191d8419346776912e6e6a1512dae91d0d2dc0/internal/processor/processor.go#L365

Proven to be working ok after a fix
Will open a PR
