### ISSUE TITLE
[Help] Dependency Track Parent Project selection

### ISSUE THREAD

**Issue by Eager2LearnTheCode** [ckotzbauer/sbom-operator#709]
Hello, 

I would like to export the SBOMS of each image as individual project from one cluster(`cluster-1`) to a specific (existing) parent project ( `cluster-1:latest`). I'm pretty unclear how could I achieve this. 
### config- values.yaml:
```yaml
args:
  targets: dtrack
  dtrack-base-url: <url>
  format: cyclonedxjson
  dtrack-parent-project-annotation-key: cluster-1
```
But for each image, operator creating a project outside cluster-1 project.

It would be nice to [map another default annotation for all the pods](https://github.com/ckotzbauer/sbom-operator/blob/main/internal/kubernetes/kubernetes.go#L112-L170) in the cluster (like the current default annotation `ckotzbauer.sbom-operator.io/<Image>`) to identify the parent project (for eg: name of the cluster) to ease the project hierarchy. 
### Annotations to all the pods in the cluster:
```
Annotation:
    ckotzbauer.sbom-operator.io/<Image>:<IMAGE_NAME>  ---> existing already
    my.parent.project/<Image>:<CLUSTER_NAME> or <value_in_config>
```

### Expected project hierarchy in DTrack:
```
cluster-1
|------- image-1
|------- image-2
|....
cluster-2
|------- image-4
|------- image-5
cluster-3
|.........
```

**Comment by Eager2LearnTheCode** [comment]
Update:
- I have created a pod as in example: https://github.com/ckotzbauer/sbom-operator?tab=readme-ov-file#example-pod-annotation and it couldn't fetch the parent project until unless the version (`cluster-1:latest`) specified as below
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-1/my-nginx: cluster-1:latest
spec:
  containers:
    - image: nginx:latest
      name: my-nginx
``` 
- Is there any other way to map additional `annotation`  by default as we have one default `ckotzbauer.sbom-operator.io/<IMAGE>`?
